### ISSUE TITLE
Error in sleuth_prep after wasabi optimized my salmon output

### ISSUE THREAD

**Issue by cayyya** [COMBINE-lab/wasabi#9]
Hello,
i've followed the user guide and processed my salmon output. However, sleuth_prep did not like how to .h5 file looks like:
> so <- sleuth_prep(s2c, ~ condition, num_cores = 1)
reading in kallisto results
dropping unused factor levels
..........
normalizing est_counts
37544 targets passed the filter
normalizing tpm
merging in metadata
summarizing bootstraps
.Error in process_bootstrap(i, samp_name, kal_path, num_transcripts, est_counts_sf[[i]],  : 
  File h5 has no bootstraps.Please generate bootstraps using "kallisto quant -b".

There is one recent report of the same problem elsewhere with no answer. Is there any solution to this?
Thank you.
Karel

**Comment by rob-p** [comment]
Hi Karel,

  I assume that salmon was, in fact, run with either bootstrapping or gibbs sampling enabled, right?  If so, would you mind providing one of these h5 files and the corresponding quant directory to help debug? In the past, such errors have been due to e.g. windows silently discarding fikes when copied over from a server.

**Comment by cayyya** [comment]
I ran Salmon using pretty much default parameters since I had no experience with similar approach before. Default means no boot strapping so it probably explained my error. I will try again with proper bootstrapping step included. Thank you.
